// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SabadinEstoqueApi.Infra;

namespace SabadinEstoqueApi.Infra.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220515230657_added_usuario")]
    partial class added_usuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SabadinEstoqueApi.Dominio.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("timestamp")
                        .HasColumnName("dataatualizacao");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("timestamp");

                    b.Property<int>("IdUsuarioAtualizacao")
                        .HasColumnType("int")
                        .HasColumnName("idusuarioalteracao");

                    b.Property<int>("IdUsuarioCadastro")
                        .HasColumnType("int")
                        .HasColumnName("idusuariocadastro");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("nome");

                    b.Property<short>("Situacao")
                        .HasColumnType("smallint")
                        .HasColumnName("situacao");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioAtualizacao");

                    b.HasIndex("IdUsuarioCadastro");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("SabadinEstoqueApi.Dominio.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("timestamp")
                        .HasColumnName("dataatualizacao");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("timestamp");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("idcategoria");

                    b.Property<int>("IdUsuarioAtualizacao")
                        .HasColumnType("int")
                        .HasColumnName("idusuarioalteracao");

                    b.Property<int>("IdUsuarioCadastro")
                        .HasColumnType("int")
                        .HasColumnName("idusuariocadastro");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("nome");

                    b.Property<int>("QtdEstoque")
                        .HasColumnType("int")
                        .HasColumnName("qtdestoque");

                    b.Property<int>("QtdEstoqueMinimo")
                        .HasColumnType("int")
                        .HasColumnName("qtdestoqueminimo");

                    b.Property<short>("Situacao")
                        .HasColumnType("smallint")
                        .HasColumnName("situacao");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal")
                        .HasColumnName("valor");

                    b.Property<decimal>("ValorPromocao")
                        .HasColumnType("decimal")
                        .HasColumnName("valorpromocao");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdUsuarioAtualizacao");

                    b.HasIndex("IdUsuarioCadastro");

                    b.ToTable("produtos");
                });

            modelBuilder.Entity("SabadinEstoqueApi.Dominio.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("codigo");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("email");

                    b.Property<int>("NivelAcesso")
                        .HasColumnType("tinyint")
                        .HasColumnName("nivelacesso");

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("senha");

                    b.Property<int>("Situacao")
                        .HasColumnType("tinyint")
                        .HasColumnName("situacao");

                    b.HasKey("Id");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("SabadinEstoqueApi.Dominio.Categoria", b =>
                {
                    b.HasOne("SabadinEstoqueApi.Dominio.Usuario", "UsuarioAlteracao")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAtualizacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SabadinEstoqueApi.Dominio.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCadastro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioAlteracao");

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("SabadinEstoqueApi.Dominio.Produto", b =>
                {
                    b.HasOne("SabadinEstoqueApi.Dominio.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SabadinEstoqueApi.Dominio.Usuario", "UsuarioAlteracao")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAtualizacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SabadinEstoqueApi.Dominio.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCadastro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("UsuarioAlteracao");

                    b.Navigation("UsuarioCadastro");
                });
#pragma warning restore 612, 618
        }
    }
}
