// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SabadinEstoqueApi.Infra;

namespace SabadinEstoqueApi.Infra.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220128020413_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SabadinEstoqueApi.Dominio.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("nome");

                    b.Property<short>("Situacao")
                        .HasColumnType("smallint")
                        .HasColumnName("situacao");

                    b.HasKey("Id");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("SabadinEstoqueApi.Dominio.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("idcategoria");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("nome");

                    b.Property<int>("QtdEstoque")
                        .HasColumnType("int")
                        .HasColumnName("qtdestoque");

                    b.Property<int>("QtdEstoqueMinimo")
                        .HasColumnType("int")
                        .HasColumnName("qtdestoqueminimo");

                    b.Property<short>("Situacao")
                        .HasColumnType("smallint")
                        .HasColumnName("situacao");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal")
                        .HasColumnName("valor");

                    b.Property<decimal>("ValorPromocao")
                        .HasColumnType("decimal")
                        .HasColumnName("valorpromocao");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.ToTable("produtos");
                });

            modelBuilder.Entity("SabadinEstoqueApi.Dominio.Produto", b =>
                {
                    b.HasOne("SabadinEstoqueApi.Dominio.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
